//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockHound
{
    using System;
    using System.Collections.Generic;
    
    public partial class Climb
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Date { get; set; }
        public string Difficulty { get; set; }
        public string Rock_Type { get; set; }
        public string Climb_Type { get; set; }
    }
}
